=== andrePankraz/seal_service/seal_verification/src/main/resources/profiles/tr_03171.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="profile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="profileNumber" type="xs:string" />
				<xs:element name="profileName" type="xs:string" />
				<xs:element name="creator" type="xs:string" />
				<xs:element name="category" type="xs:string"
					minOccurs="0" />
				<xs:element name="leikaID" type="xs:string" minOccurs="0" />
				<xs:element name="entry" type="entryType" minOccurs="1"
					maxOccurs="251" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="tagNo">
			<xs:selector xpath="entry" />
			<xs:field xpath="@tag" />
		</xs:unique>
	</xs:element>
	<xs:complexType name="entryType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="length" type="xs:positiveInteger"
				minOccurs="0" />
			<xs:element name="type" type="typeType" />
			<xs:element name="defaultValue" type="xs:string"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="tag" type="tagType" use="required" />
		<xs:attribute name="optional" type="xs:boolean" />
	</xs:complexType>
	<xs:simpleType name="typeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="alphanum" />
			<xs:enumeration value="string" />
			<xs:enumeration value="multistring" />
			<xs:enumeration value="binary" />
			<xs:enumeration value="date" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tagType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="4" />
			<xs:maxInclusive value="254" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== andrePankraz/seal_service/seal_verification/src/main/resources/profiles/ZAB001.xml
<?xml version="1.0" encoding="UTF-8"?>
<profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="tr_03171.xsd">
	<profileNumber>ZAB001</profileNumber>
	<profileName>ZAB Zeugnisbewertung (Version 1)</profileName>
	<creator>ZAB</creator>
	<category>TODO</category>
	<leikaID>TODO</leikaID>
	<entry optional="false" tag="4">
		<name>Urkundennummer</name>
		<description>description</description>
		<length>15</length>
		<type>string</type>
	</entry>
	<entry optional="false" tag="5">
		<name>Name</name>
		<description>description</description>
		<length>30</length>
		<type>string</type>
	</entry>
	<entry optional="false" tag="6">
		<name>Vorname</name>
		<description>description</description>
		<length>30</length>
		<type>string</type>
	</entry>
	<entry optional="false" tag="7">
		<name>Geburtsdatum</name>
		<description>description</description>
		<type>date</type>
	</entry>
	<entry optional="false" tag="8">
		<name>Abschlussbezeichnung</name>
		<description>description</description>
		<length>60</length>
		<type>string</type>
	</entry>
	<entry optional="false" tag="9">
		<name>Bewertung</name>
		<description>description</description>
		<length>200</length>
		<type>string</type>
	</entry>
</profile>
